services:
    frontend:
        image: node:16
        container_name: doglist-frontend
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "8081:8081"
        networks:
            - doglist-network
        command: sh -c "npm install && npm run serve"

networks:
    doglist-network:
        driver: bridge